version: "3.4"

services:
  EasyAnime:
    image: "eling486/easy_anime:latest"
    container_name: "easy_anime"
    restart: unless-stopped
    ports:
      - "3486:3486"
    volumes:
      - "./:/app/data"
    network_mode: bridge
    environment:
      - TZ=Asia/Shanghai
      - PGID=1000
      - PUID=1000
      - UMASK=022